/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package botao;

/**
 *
 * @author SCCSBT
 */
public class TesteTelaBo extends javax.swing.JFrame {

    /**
     * Creates new form TesteTelaBo
     */
    public TesteTelaBo() {
        initComponents();
        painelText.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelText = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTeste = new javax.swing.JButton();
        lblPergunta = new javax.swing.JLabel();
        btnSim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("<html>Todos sabemos a resposta certa ;D</html>");

        javax.swing.GroupLayout painelTextLayout = new javax.swing.GroupLayout(painelText);
        painelText.setLayout(painelTextLayout);
        painelTextLayout.setHorizontalGroup(
            painelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTextLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(114, 114, 114))
        );
        painelTextLayout.setVerticalGroup(
            painelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTextLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 131, Short.MAX_VALUE))
        );

        getContentPane().add(painelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 172, -1, 180));

        btnTeste.setText("Programar");
        btnTeste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTesteMouseEntered(evt);
            }
        });
        btnTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTesteActionPerformed(evt);
            }
        });
        getContentPane().add(btnTeste, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 91, -1));

        lblPergunta.setText("<html>Quando se trata de desenvolvimento, o que o DEV prefere?</html>");
        getContentPane().add(lblPergunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 240, 55));

        btnSim.setText("Documentar");
        btnSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimActionPerformed(evt);
            }
        });
        getContentPane().add(btnSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 101, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTesteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTesteActionPerformed


    private void btnTesteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTesteMouseEntered
        // TODO add your handling code here:
        double ale = Math.random();
        double ale2 = Math.random();
        int x = (int) (1 + ale * (309 - 1));
        int y = (int) (1 + ale2 * (277 - 1));
        btnTeste.setLocation(x, y);
    }//GEN-LAST:event_btnTesteMouseEntered

    private void btnSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimActionPerformed
        // TODO add your handling code here:
        painelText.setVisible(true);
        btnTeste.setVisible(false);
        btnSim.setVisible(false);
        lblPergunta.setVisible(false);
    }//GEN-LAST:event_btnSimActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteTelaBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteTelaBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteTelaBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteTelaBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteTelaBo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSim;
    private javax.swing.JButton btnTeste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JPanel painelText;
    // End of variables declaration//GEN-END:variables
}
